<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AdminSysteme extends \App\Entity\AdminSysteme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'id', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'NomComplet', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'Email', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'Motdepasse', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'créerPartenaire', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'CreerCaissier'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'id', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'NomComplet', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'Email', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'Motdepasse', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'créerPartenaire', '' . "\0" . 'App\\Entity\\AdminSysteme' . "\0" . 'CreerCaissier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AdminSysteme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomComplet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomComplet', []);

        return parent::getNomComplet();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomComplet(string $NomComplet): \App\Entity\AdminSysteme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomComplet', [$NomComplet]);

        return parent::setNomComplet($NomComplet);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $Email): \App\Entity\AdminSysteme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$Email]);

        return parent::setEmail($Email);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotdepasse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotdepasse', []);

        return parent::getMotdepasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotdepasse(string $Motdepasse): \App\Entity\AdminSysteme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotdepasse', [$Motdepasse]);

        return parent::setMotdepasse($Motdepasse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCréerPartenaire(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCréerPartenaire', []);

        return parent::getCréerPartenaire();
    }

    /**
     * {@inheritDoc}
     */
    public function addCrErPartenaire(\App\Entity\Partenaire $crErPartenaire): \App\Entity\AdminSysteme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCrErPartenaire', [$crErPartenaire]);

        return parent::addCrErPartenaire($crErPartenaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCrErPartenaire(\App\Entity\Partenaire $crErPartenaire): \App\Entity\AdminSysteme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCrErPartenaire', [$crErPartenaire]);

        return parent::removeCrErPartenaire($crErPartenaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreerCaissier(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreerCaissier', []);

        return parent::getCreerCaissier();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreerCaissier(\App\Entity\Caissier $creerCaissier): \App\Entity\AdminSysteme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreerCaissier', [$creerCaissier]);

        return parent::addCreerCaissier($creerCaissier);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreerCaissier(\App\Entity\Caissier $creerCaissier): \App\Entity\AdminSysteme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreerCaissier', [$creerCaissier]);

        return parent::removeCreerCaissier($creerCaissier);
    }

}
