<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Caissier extends \App\Entity\Caissier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Identite', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Contact', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'NumeroIdentite', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Login', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Motdepasse', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'adminSysteme', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Montantverse'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Identite', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Nom', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Prenom', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Contact', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'NumeroIdentite', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Login', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Motdepasse', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'adminSysteme', '' . "\0" . 'App\\Entity\\Caissier' . "\0" . 'Montantverse'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Caissier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentite', []);

        return parent::getIdentite();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentite(string $Identite): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentite', [$Identite]);

        return parent::setIdentite($Identite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $Nom): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$Nom]);

        return parent::setNom($Nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $Prenom): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$Prenom]);

        return parent::setPrenom($Prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $Adresse): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$Adresse]);

        return parent::setAdresse($Adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', []);

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact(int $Contact): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', [$Contact]);

        return parent::setContact($Contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroIdentite(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroIdentite', []);

        return parent::getNumeroIdentite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroIdentite(int $NumeroIdentite): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroIdentite', [$NumeroIdentite]);

        return parent::setNumeroIdentite($NumeroIdentite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogin', []);

        return parent::getLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogin(string $Login): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogin', [$Login]);

        return parent::setLogin($Login);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotdepasse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotdepasse', []);

        return parent::getMotdepasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotdepasse(string $Motdepasse): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotdepasse', [$Motdepasse]);

        return parent::setMotdepasse($Motdepasse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminSysteme(): ?\App\Entity\AdminSysteme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminSysteme', []);

        return parent::getAdminSysteme();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminSysteme(?\App\Entity\AdminSysteme $adminSysteme): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminSysteme', [$adminSysteme]);

        return parent::setAdminSysteme($adminSysteme);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantverse(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantverse', []);

        return parent::getMontantverse();
    }

    /**
     * {@inheritDoc}
     */
    public function addMontantverse(\App\Entity\Versement $montantverse): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMontantverse', [$montantverse]);

        return parent::addMontantverse($montantverse);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMontantverse(\App\Entity\Versement $montantverse): \App\Entity\Caissier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMontantverse', [$montantverse]);

        return parent::removeMontantverse($montantverse);
    }

}
