<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fpUTOXz' shared service.

return $this->privates['.service_locator.fpUTOXz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminSystemeController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\CaissierController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PartenaireController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SousPartenaireController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\VersementController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\AdminSystemeController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\CaissierController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\PartenaireController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\SousPartenaireController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\VersementController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
], [
    'App\\Controller\\AdminSystemeController::setViewHandler' => '?',
    'App\\Controller\\CaissierController::setViewHandler' => '?',
    'App\\Controller\\PartenaireController::setViewHandler' => '?',
    'App\\Controller\\SousPartenaireController::setViewHandler' => '?',
    'App\\Controller\\VersementController::setViewHandler' => '?',
    'App\\Controller\\AdminSystemeController:setViewHandler' => '?',
    'App\\Controller\\CaissierController:setViewHandler' => '?',
    'App\\Controller\\PartenaireController:setViewHandler' => '?',
    'App\\Controller\\SousPartenaireController:setViewHandler' => '?',
    'App\\Controller\\VersementController:setViewHandler' => '?',
]);
