<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOojpfGi\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOojpfGi/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerOojpfGi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerOojpfGi\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerOojpfGi\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'OojpfGi',
    'container.build_id' => '684852c3',
    'container.build_time' => 1564475431,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOojpfGi');
