<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXAxsiaX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXAxsiaX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXAxsiaX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXAxsiaX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXAxsiaX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XAxsiaX',
    'container.build_id' => '88fa3afe',
    'container.build_time' => 1564483067,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXAxsiaX');
